// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF31X3OasKLP3Lt7CmXP0r74cng_8arQQ',
    appId: '1:112425397236:web:2af4e599778f4bfccbe7a1',
    messagingSenderId: '112425397236',
    projectId: 'movieappflutter-7d810',
    authDomain: 'movieappflutter-7d810.firebaseapp.com',
    storageBucket: 'movieappflutter-7d810.firebasestorage.app',
    measurementId: 'G-BPPRG2X8FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_LBhVWj9v2ZmZqFGoEQCBca-c8_CNIk',
    appId: '1:112425397236:android:78bd68ef989dd81bcbe7a1',
    messagingSenderId: '112425397236',
    projectId: 'movieappflutter-7d810',
    storageBucket: 'movieappflutter-7d810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH3Rm_F4wbnWDLU0YOMATSrHXvF4Ivd4A',
    appId: '1:112425397236:ios:9cc2366b60bfca1bcbe7a1',
    messagingSenderId: '112425397236',
    projectId: 'movieappflutter-7d810',
    storageBucket: 'movieappflutter-7d810.firebasestorage.app',
    iosBundleId: 'com.example.movieWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH3Rm_F4wbnWDLU0YOMATSrHXvF4Ivd4A',
    appId: '1:112425397236:ios:9cc2366b60bfca1bcbe7a1',
    messagingSenderId: '112425397236',
    projectId: 'movieappflutter-7d810',
    storageBucket: 'movieappflutter-7d810.firebasestorage.app',
    iosBundleId: 'com.example.movieWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF31X3OasKLP3Lt7CmXP0r74cng_8arQQ',
    appId: '1:112425397236:web:1f010567dd89257fcbe7a1',
    messagingSenderId: '112425397236',
    projectId: 'movieappflutter-7d810',
    authDomain: 'movieappflutter-7d810.firebaseapp.com',
    storageBucket: 'movieappflutter-7d810.firebasestorage.app',
    measurementId: 'G-5XZ12NV3W1',
  );

}